SETTING:
  DIR_HOME: "../" # プロジェクトのホームディレクトリ
  DIR_MODEL: "../models/" # 学習結果の諸々を保存するディレクトリ
  DIR_SUBMISSION: "../data/submission/" # sample提出ファイル保存ディレクトリ
  DIR_INTERIM: "../data/interim/" # オリジナルデータ
  DIR_FEATURE: "../data/features/" # 特徴量データの格納先ディレクトリ
  DIR_FIGURE: "../data/figures/" # 図表の保存先ディレクトリ
  DIR_INPUT: "../data/raw/input" # オリジナルデータ
  DIR_LOG: "../logs/" # ログの保存先ディレクトリ
  FILE_NAME_SAMPLE_SUBMISSION: "sample_submit.csv" # sample_submissionファイルの名前
  FILE_NAME_STATION: "station.csv" # stationデータの名前
  FILE_NAME_WEATHER: "weather.csv" # weatherデータの名前
  FILE_NAME_STATUS: "status.csv" # statusデータの名前
  FILE_NAME_TRIP: "trip.csv" # tripデータの名前
  TARGET_COL: "" # 目的変数
  REMOVE_COLS: [] # trainデータから削除するカラム
  KEY_COL: [""] # key